language: java

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz
 
script:
- ls -alF
- java -jar plantuml.jar composition.txt
- ls -alF

# if everything OK, then deploy on the web
after_success: 
#- bash update.sh
- echo -e "Starting to update gitHub\n"
- git config --global user.email "jbruel#travis@gmail.com"
- git config --global user.name "Jean-Michel Bruel"
#git config --global push.default simple

#using token clone io pages branch
#git clone --quiet https://github.com/jmbruel/basics.git travis > /dev/null

#go into directory and copy data we're interested in to that directory
#cd travis
#cp $HOME/output/*.png .
#ls -al 

#add, commit and push files without provoking Continuous Integration
#git add *.png
- git commit -am "Travis build $TRAVIS_BUILD_NUMBER pushed to basics repository -- [skip ci]"
- git push -fq origin master

- echo -e "Done magic with output\n"
