language: java

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz
 
script:
- ls -alF
- make *.png

# if everything OK, then deploy on the web
after_success: 
- bash update.sh
