basics
======
:github: https://github.com[GitHub]
:plantUML: http://plantuml.sourceforge.net/[plantUML]
:travis: https://travis-ci.org[Travis]
:uri-ci-travis: https://travis-ci.org/jmbruel/basics
// Thanks Dan Alen for the following
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
ifndef::icons[:conum-guard: {sp}#{sp}]

ifdef::status[]
image:https://img.shields.io/badge/license-MIT-blue.svg[MIT License, link=#copyright-and-license]
image:https://img.shields.io/travis/jmbruel/basics/master.svg[Build Status (Travis CI), link={uri-ci-travis}]
endif::[]

Basic UML concepts and diagrams in {plantUML} for easy modification/translation.

Last CI status: image:https://travis-ci.org/jmbruel/basics.svg?branch=master["Build Status (Travis CI)", link={uri-ci-travis}"]
(Fork me on https://github.com/jmbruel/basics[icon:github[] GitHub])


== How To

[NOTE]
====
All the +.plantuml+ files are simple text files written using {plantUML} textual notation.
====

To add a concept:

. Add a new +.plantuml+ file (take example on an existing one such as link:class.plantuml[])
. Generate the corresponding +.svg+ or +.png+ file (you can use the proposed link:Makefile[]
by simply launching `make build` or the following command)
+
....
make outpout/myNewFile.svg
....
+
[NOTE]
====
If you don't have {plantUML}, you can simply add your +.plantuml+ file. {github} will
generate the +.png+ file for you using {travis}. But you'll have to remove the
+-- [skip ci]+ comment in the commit message below.

Note also that {travis} can be very slow.
====
+
. Add your name in the contributors' list (if not done already)
. Share with others!
+
....
git add myNewFile.plantuml output/myNewFile.png
git commit -am "myAwesomeMessage -- [skip ci]"
git push
....

== Contributors

- mailto:jbruel@gmail.com[J.-M. Bruel] (U. of Toulouse)

== Copyright and License

Copyright (C) 2014-2017 Jean-Michel Bruel.
Free use of this software is granted under the terms of the MIT License.
See <<LICENSE#,LICENSE>> for details.
