basics
======
:github: https://github.com[GitHub]
:plantUML: http://plantuml.sourceforge.net/[plantUML]
:travis: https://travis-ci.org[Travis]

Basic UML concepts and diagrams in {plantUML} for easy modification/translation

== How To

[NOTE]
====
All the +.txt+ files are written using {plantUML} textual notation.
====

To add a concept:

. Add a new +.txt+ file (take example on an existing one such as link:class.txt[])
. Generate the corresponding +.png+ file (you can use the proposed link:Makefile[])
+
....
make myNewFile.png
....
+
[NOTE]
====
If you don't have {plantUML}, you can simply add your +.txt+ file. {github} will
generate the +.png+ file for you using {travis}. But you'll have to remove the
+-- [skip ci]+ comment in the commit message below. Note also that {travis} can be very
slow.
====
+
. Add your name in the contributors' list (if not done already)
. Share with others!
+
....
git add myNewFile.*
git commit -am "myAwesomeMessage -- [skip ci]"
git push
....

== Contributors

- mailto:jbruel@gmail.com[J.-M. Bruel] (U. of Toulouse)