'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------
@startuml
' File where const and funcitons are defined:
!include Defs.txt
'-----------------------------------

[*] --> Comp

state COMPOSITE as Comp {
  state IDLE as Idle
  state CONFIG as Configuring
  [*] --> Idle
  Idle --> Configuring : Ev1
  Configuring --> Idle : Ev2
}

@enduml
